package com.fincons.day7.entity;

import com.fincons.day7.entity.enums.Status;
import jakarta.persistence.*;

/**
 * Represents a Task entity in the application.
 * This entity is mapped to a database table named "task".
 */
@Entity
@Table(name = "task")
public class Task {
    /**
     * Unique identifier for the task.
     * It is the primary key and is auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * The title or description of the task. Cannot be null.
     */
    @Column(nullable = false)
    private String title;

    /**
     * The current status of the task (PENDING or COMPLETED). Cannot be null.
     * Stored as a string in the database.
     */
    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private Status status;

    /**
     * The user to whom this task is assigned.
     * Many tasks can belong to one user (Many-to-One relationship).
     * The 'user_id' column in the 'task' table acts as the foreign key.
     * FetchType.LAZY means the user data is loaded only when explicitly accessed.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id", nullable = false)
    private User user;

    /**
     * Enum to define the possible statuses for a task.
     */


    // Getters and Setters for all fields
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public Status getStatus() {
        return status;
    }

    public void setStatus(Status status) {
        this.status = status;
    }

    public User getUser() {
        return user;
    }

    public void setUser(User user) {
        this.user = user;
    }
}
