package com.fincons.day7.entity;

import jakarta.persistence.*;

import java.util.List;

/**
 * Represents a User entity in the application.
 * This entity is mapped to a database table named "user".
 * The table name is quoted to avoid conflicts with PostgreSQL reserved keywords.
 */
@Entity
@Table(name = "\"user\"") // Quoting the table name for PostgreSQL compatibility
public class User {
    /**
     * Unique identifier for the user.
     * It is the primary key and is auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * The name of the user. Cannot be null.
     */
    @Column(nullable = false)
    private String name;

    /**
     * The email address of the user. Cannot be null and must be unique.
     */
    @Column(nullable = false, unique = true)
    private String email;

    /**
     * Indicates if the user account is active. Defaults to true.
     */
    @Column(nullable = false)
    private boolean active = true;

    /**
     * A list of tasks associated with this user.
     * One user can have multiple tasks (One-to-Many relationship).
     * CascadeType.ALL ensures that all operations (persist, remove, refresh, merge, detach)
     * are cascaded from the User to its associated Tasks.
     * orphanRemoval = true means that if a task is removed from the user's task list,
     * it will be removed from the database.
     */
    @OneToMany(mappedBy = "user", cascade = CascadeType.ALL, orphanRemoval = true)
    private List<Task> tasks;

    // Getters and Setters for all fields

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public boolean isActive() {
        return active;
    }

    public void setActive(boolean active) {
        this.active = active;
    }

    public List<Task> getTasks() {
        return tasks;
    }

    public void setTasks(List<Task> tasks) {
        this.tasks = tasks;
    }
}
